title: "Jacob Duffy"
author: "Jacob Duffy"
description: "© 2024 Jacob Duffy. All rights reserved.<br>Github page theme: <a href=https://github.com/niklasbuschmann/contrast>contrast</a><br>Last updated: 8/25"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "about.markdown"}
  - {file: "research.markdown"}
  - {file: "cv.markdown"}
  - {file: "contact.markdown"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:jod0007@auburn.edu"}
  - {title: Github, icon: github, url: "https://github.com/jduffy0121"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
